"""
image_registry.py — MapArr Image DB.

Loads a JSON knowledge base of Docker images and provides lookup methods
for role classification, image family identification, and keyword sets.

Two-layer data model:
  - Families: UID/GID conventions (LinuxServer.io, Hotio, jlesage, etc.)
  - Images: role + family + matching patterns + keywords

Data sources:
  - data/images.json — baked-in, generated by scripts/seed_images.py
  - data/custom-images.json — optional user overrides (mounted via compose)

This module replaces the hardcoded ARR_APPS, DOWNLOAD_CLIENTS, MEDIA_SERVERS
sets and IMAGE_FAMILIES list that were previously in analyzer.py.
"""

import json
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger("maparr.registry")

# Hardcoded safety net — if images.json is missing or corrupt, MapArr
# can still classify the most common services. This is the minimum viable
# set, not the full DB. Users should never hit this in normal operation.
_FALLBACK_IMAGES = {
    "sonarr": {"name": "Sonarr", "role": "arr", "keywords": ["sonarr"]},
    "radarr": {"name": "Radarr", "role": "arr", "keywords": ["radarr"]},
    "lidarr": {"name": "Lidarr", "role": "arr", "keywords": ["lidarr"]},
    "readarr": {"name": "Readarr", "role": "arr", "keywords": ["readarr"]},
    "whisparr": {"name": "Whisparr", "role": "arr", "keywords": ["whisparr"]},
    "prowlarr": {"name": "Prowlarr", "role": "arr", "keywords": ["prowlarr"]},
    "bazarr": {"name": "Bazarr", "role": "arr", "keywords": ["bazarr"]},
    "overseerr": {"name": "Overseerr", "role": "request", "keywords": ["overseerr"]},
    "jellyseerr": {"name": "Jellyseerr", "role": "request", "keywords": ["jellyseerr"]},
    "ombi": {"name": "Ombi", "role": "request", "keywords": ["ombi"]},
    "qbittorrent": {"name": "qBittorrent", "role": "download_client", "keywords": ["qbittorrent", "qbit"]},
    "sabnzbd": {"name": "SABnzbd", "role": "download_client", "keywords": ["sabnzbd", "sab", "nzb"]},
    "nzbget": {"name": "NZBGet", "role": "download_client", "keywords": ["nzbget"]},
    "transmission": {"name": "Transmission", "role": "download_client", "keywords": ["transmission"]},
    "deluge": {"name": "Deluge", "role": "download_client", "keywords": ["deluge"]},
    "rtorrent": {"name": "rTorrent", "role": "download_client", "keywords": ["rtorrent"]},
    "jdownloader": {"name": "JDownloader", "role": "download_client", "keywords": ["jdownloader", "jdown", "jd2"]},
    "aria2": {"name": "aria2", "role": "download_client", "keywords": ["aria2"]},
    "flood": {"name": "Flood", "role": "download_client", "keywords": ["flood"]},
    "rdtclient": {"name": "RDTClient", "role": "download_client", "keywords": ["rdtclient"]},
    "plex": {"name": "Plex", "role": "media_server", "keywords": ["plex"]},
    "jellyfin": {"name": "Jellyfin", "role": "media_server", "keywords": ["jellyfin"]},
    "emby": {"name": "Emby", "role": "media_server", "keywords": ["emby"]},
}

# Roles that participate in hardlink analysis (for fallback mode)
_HARDLINK_ROLES = {"arr", "download_client", "media_server"}
_NON_HARDLINK_FALLBACK = {"prowlarr", "bazarr"}


class ImageRegistry:
    """Docker image knowledge base with role classification and family lookup."""

    def __init__(self):
        self._families: dict[str, dict] = {}
        self._images: dict[str, dict] = {}
        # Indexes built on load
        self._by_pattern: list[tuple[str, dict]] = []
        self._by_keyword: list[tuple[str, dict]] = []
        self._all_keywords: set[str] = set()
        self._keywords_by_role: dict[str, set[str]] = {}
        self._hardlink_keywords: set[str] = set()
        # Family-level pattern index for get_family() fallback
        self._family_by_pattern: list[tuple[str, dict]] = []
        self._loaded = False

    @property
    def image_count(self) -> int:
        return len(self._images)

    @property
    def family_count(self) -> int:
        return len(self._families)

    def load(self, data_dir: Path | str) -> None:
        """Load the Image DB from data_dir/images.json.

        Optionally merges data_dir/custom-images.json if it exists.
        Falls back to hardcoded safety net if the main file is missing or corrupt.
        """
        data_dir = Path(data_dir)
        main_file = data_dir / "images.json"
        custom_file = data_dir / "custom-images.json"

        # Load main DB
        data = self._read_json(main_file)
        if data is None:
            logger.warning("Image DB not found at %s — using fallback data", main_file)
            self._load_fallback()
            return

        self._families = data.get("families", {})
        self._images = data.get("images", {})

        # Merge custom overrides
        if custom_file.exists():
            custom = self._read_json(custom_file)
            if custom:
                custom_families = custom.get("families", {})
                custom_images = custom.get("images", {})
                self._families.update(custom_families)
                self._images.update(custom_images)
                total_custom = len(custom_families) + len(custom_images)
                logger.info("ImageRegistry: merged %d custom entries from custom-images.json",
                            total_custom)

        self._build_indexes()
        self._loaded = True
        logger.info("ImageRegistry: loaded %d images, %d families",
                     self.image_count, self.family_count)

    def _read_json(self, path: Path) -> Optional[dict]:
        """Read and parse a JSON file. Returns None on any error."""
        if not path.exists():
            return None
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            if not isinstance(data, dict):
                logger.warning("Image DB at %s is not a JSON object", path)
                return None
            return data
        except (json.JSONDecodeError, OSError) as e:
            logger.warning("Failed to read Image DB at %s: %s", path, e)
            return None

    def _load_fallback(self) -> None:
        """Load the hardcoded safety net when images.json is unavailable."""
        self._families = {}
        self._images = {}
        for key, entry in _FALLBACK_IMAGES.items():
            self._images[key] = {
                "name": entry["name"],
                "role": entry["role"],
                "family": None,
                "patterns": [],
                "keywords": entry["keywords"],
                "hardlink_capable": (
                    entry["role"] in _HARDLINK_ROLES and key not in _NON_HARDLINK_FALLBACK
                ),
                "docs_url": None,
            }
        self._build_indexes()
        self._loaded = True
        logger.info("ImageRegistry: fallback mode — %d images, 0 families", self.image_count)

    def _build_indexes(self) -> None:
        """Build lookup indexes from loaded data."""
        self._by_pattern = []
        self._by_keyword = []
        self._all_keywords = set()
        self._keywords_by_role = {}
        self._hardlink_keywords = set()
        self._family_by_pattern = []

        # Build family-level pattern index (for get_family() fallback).
        # Families can declare image_patterns like ["hotio/", "cr.hotio.dev/hotio/"]
        # so any image from that registry is recognized even without a specific
        # image entry in the DB.
        for _key, family in self._families.items():
            for pattern in family.get("image_patterns", []):
                self._family_by_pattern.append((pattern.lower(), family))
        # Sort longest-first so more specific patterns win
        self._family_by_pattern.sort(key=lambda x: -len(x[0]))

        for _key, entry in self._images.items():
            role = entry.get("role", "other")
            keywords = entry.get("keywords", [])
            hardlink = entry.get("hardlink_capable", False)

            # Pattern index (sorted longest-first for greedy matching)
            for pattern in entry.get("patterns", []):
                self._by_pattern.append((pattern.lower(), entry))

            # Keyword index
            for kw in keywords:
                kw_lower = kw.lower()
                self._by_keyword.append((kw_lower, entry))
                self._all_keywords.add(kw_lower)

                # Keywords by role
                if role not in self._keywords_by_role:
                    self._keywords_by_role[role] = set()
                self._keywords_by_role[role].add(kw_lower)

                # Hardlink participants
                if hardlink:
                    self._hardlink_keywords.add(kw_lower)

        # Sort longest-first so more specific entries match first.
        # Prevents "nzb" from matching before "nzbget", etc.
        self._by_pattern.sort(key=lambda x: -len(x[0]))
        self._by_keyword.sort(key=lambda x: -len(x[0]))

    def classify(self, service_name: str, image: str) -> dict:
        """Classify a Docker service by its role in the media stack.

        Tries image string pattern matching first (precise), then falls
        back to service name keyword matching (fuzzy).

        Returns a dict with: role, family_name, name, hardlink_capable, docs_url
        """
        image_lower = image.lower() if image else ""
        name_lower = service_name.lower() if service_name else ""

        # Pass 1: match image string against patterns
        for pattern, entry in self._by_pattern:
            if pattern in image_lower:
                return self._make_result(entry)

        # Pass 2: match service name against keywords
        for kw, entry in self._by_keyword:
            if kw in name_lower:
                return self._make_result(entry)

        # Pass 3: match image string against keywords (catches custom registries)
        for kw, entry in self._by_keyword:
            if kw in image_lower:
                return self._make_result(entry)

        # No match
        return {
            "role": "other",
            "family_name": None,
            "name": None,
            "hardlink_capable": False,
            "docs_url": None,
        }

    def _make_result(self, entry: dict) -> dict:
        """Build a classification result dict from an image entry."""
        family_key = entry.get("family")
        family = self._families.get(family_key) if family_key else None
        return {
            "role": entry.get("role", "other"),
            "family_name": family["name"] if family else None,
            "name": entry.get("name"),
            "hardlink_capable": entry.get("hardlink_capable", False),
            "docs_url": entry.get("docs_url"),
        }

    def get_family(self, image: str) -> Optional[dict]:
        """Look up the image family for a Docker image string.

        Returns the family dict (with uid_env, gid_env, etc.) or None.

        Family-level patterns are the source of truth for UID/GID conventions.
        An image like `hotio/radarr` may appear in the radarr image entry
        (which has family=linuxserver for LSIO defaults), but the *family*
        for that specific image string is Hotio — which has different default
        UIDs. So we match family patterns first, then fall back to image entries.
        """
        image_lower = image.lower() if image else ""

        # Pass 1: match against family-level patterns (authoritative for UID/GID)
        # Sorted longest-first, so "cr.hotio.dev/hotio/" beats "hotio/"
        for pattern, family in self._family_by_pattern:
            if pattern in image_lower:
                return family

        # Pass 2: match image against specific image entry patterns
        for pattern, entry in self._by_pattern:
            if pattern in image_lower:
                family_key = entry.get("family")
                if family_key:
                    return self._families.get(family_key)
                return None

        return None

    def known_keywords(self) -> set[str]:
        """Return all known service keywords (for parser recognition)."""
        return set(self._all_keywords)

    def known_by_role(self, role: str) -> set[str]:
        """Return keywords for a specific role."""
        return set(self._keywords_by_role.get(role, set()))

    def hardlink_participants(self) -> set[str]:
        """Return keywords for services that participate in hardlink analysis."""
        return set(self._hardlink_keywords)


# ─── Module-Level Singleton ───
# Lazy-loaded on first access. Lives here (not in main.py) to avoid
# circular imports: main.py → pipeline.py → analyzer.py → registry.

_registry: Optional[ImageRegistry] = None


def get_registry() -> ImageRegistry:
    """Return the global ImageRegistry singleton, loading it on first call.

    The data directory is resolved relative to this file's location:
    image_registry.py is in backend/, so data/ is at ../data/.
    """
    global _registry
    if _registry is None:
        _registry = ImageRegistry()
        data_dir = Path(__file__).parent.parent / "data"
        _registry.load(data_dir)
    return _registry
